# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.URLField(default=django.utils.timezone.now, max_length=299),
            preserve_default=False,
        ),
    ]
